{
    'name': 'Hostel management',
    'version': '17.0.1.0.0',
    'license': 'AGPL-3',
    'author': 'Serhii Vydysh',
    'depends': ['base',
                ],
    'data': [
        'security/hostel_groups.xml',
        'security/ir.model.access.csv',
        'views/hostel_menus.xml',
        'views/hostel_service_type_views.xml',
        'views/hostel_service_views.xml',
        'views/hostel_bed_views.xml',
        'views/res_partner_views.xml',
        'views/hostel_room_views.xml',
        'views/hostel_payment_views.xml',
        'wizard/create_booking_wizard_views.xml',
        'views/hostel_booking_views.xml',
        'report/report_booking.xml',
    ],
    'demo': [
        'demo/hostel_demo.xml',
    ],
    'application': False,
    'installable': True,
    'auto_install': False,
    'readme': 'README.rst',
}
